# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170911_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание'),
        ),
    ]
